apiVersion: v1
kind: Service
metadata:
  name: devsecops
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: devsecops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80
